app/src/objects/Achievement__c.object
<CustomObject>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

app/src/objects/Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Enable_Self_Registration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if you&apos;d like to make this training plan available to all your company and allow users to create assignments on-the-fly.</description>
        <inlineHelpText>Check this box if you&apos;d like to make this training plan available to all your company and allow users to create assignments on-the-fly.</inlineHelpText>
        <label>Enable Self-Registration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Self_Registration_Access__c</fullName>
        <inlineHelpText>&quot;Public&quot; or empty access allows any users to create assignments &quot;on the fly&quot; for this training plan. &quot;Requires Approval&quot; logs an approval request that is later handled by the Training Plan owner.</inlineHelpText>
        <label>Self-Registration Access</label>
        <picklist>
            <controllingField>Enable_Self_Registration__c</controllingField>
            <picklistValues>
                <fullName>Public</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Requires Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Training Plan</label>
    <nameField>
        <label>Training Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Training_Plan__c.object
    <fields>
        <fullName>New_Until__c</fullName>
        <inlineHelpText>Display a New ribbon in the training plan until the specified date</inlineHelpText>
        <label>New Until</label>
        <type>Date</type>
    </fields>

app/src/classes/TrainingPlanWithAchievement.cls
/*
Copyright (c) 2014, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

*/
public with sharing class TrainingPlanWithAchievement {
    public Id planId {get;private set;}
    public transient String planName {get;private set;}
    public transient String planDescription {get; private set;}
    public transient String planDetailURL {get; private set;}
    public transient String planAccess{get;private set;}
    public transient String planEndDate{get;private set;}
    public transient String planCompletedDate{get;set;}
    public transient Achievement__c mainAchievement {get; private set;}
    public transient Boolean hasAssignment{get;set;}
    public transient String assignmentStatus{get;set;}
    public transient Boolean selfRegistrationEnabled{get;set;}
    public transient Date newUntil{get;set;}

    public TrainingPlanWithAchievement(Training_Plan__c tplan, Achievement__c tachievement,String detailURL, Boolean hasAssignment){
        planName = tplan.Name;
        planId = tplan.Id;
        planAccess = tplan.Self_Registration_Access__c;
        planDescription = tplan.Description__c;
        newUntil = tplan.New_Until__c;
        selfRegistrationEnabled = tplan.Enable_Self_Registration__c;
        if(detailURL != null){
            planDetailURL = detailURL+'?id='+tplan.Id;
        }
        mainAchievement = tachievement;
        assignmentStatus = null;
        this.hasAssignment = hasAssignment;
        if(tplan.End_Date__c != null){
            planEndDate = (tplan.End_Date__c).format();
        }
        planCompletedDate = null;
    }
}