app/src/objects/Almond_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings used by the almond app</description>
    <fields>
        <fullName>Company_Logo__c</fullName>
        <description>URL for your company logo</description>
        <inlineHelpText>URL for your company logo</inlineHelpText>
        <label>Company Logo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Header_Background_Color__c</fullName>
        <description>HEX value for the header background color. (e.g. #EEEEEE)</description>
        <inlineHelpText>HEX value for the header background color. (e.g. #EEEEEE)</inlineHelpText>
        <label>Header Background Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Header_Text_Color__c</fullName>
        <description>HEX value for the header text color. (e.g. #EEEEEE)</description>
        <inlineHelpText>HEX value for the header text color. (e.g. #EEEEEE)</inlineHelpText>
        <label>Header Text Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Header_Text_Hover_Color__c</fullName>
        <description>HEX value for the header text hover color. (e.g. #EEEEEE)</description>
        <inlineHelpText>HEX value for the header text hover color. (e.g. #EEEEEE)</inlineHelpText>
        <label>Header Text Hover Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disable_Track_Achievements__c</fullName>
        <inlineHelpText>Enable this option to prevent automatic achievement assignment for track achievements</inlineHelpText>
        <defaultValue>false</defaultValue>
        <label>Disable Track Achievements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Future_Progress_Calculation__c</fullName>
        <inlineHelpText>Enable this option to force training plan progress calculation in a single transaction</inlineHelpText>
        <defaultValue>false</defaultValue>
        <label>Disable Future Progress Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_iOS_Tap_Fix__c</fullName>
        <inlineHelpText>Enable this option if you're experiencing issues with taps in Salesforce1 + iOS8</inlineHelpText>
        <defaultValue>false</defaultValue>
        <label>Enable iOS Tap Fix</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Salesforce_Header__c</fullName>
        <inlineHelpText>Enable this option to show the Salesforce header for the end-user training pages</inlineHelpText>
        <defaultValue>false</defaultValue>
        <label>Show Salesforce Header</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Correct_Response_Checkbox__c</fullName>
        <inlineHelpText>Enable this option if you'd like to disable setting the correct response checkbox on every response</inlineHelpText>
        <defaultValue>false</defaultValue>
        <label>Disable Correct Response Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Feed_Item_Audit_Fields__c</fullName>
        <inlineHelpText>Enable this option if you'd like to disable setting the created by id for achievement feed items</inlineHelpText>
        <defaultValue>false</defaultValue>
        <label>Disable Audit Fields for Feed Items</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Back_to_SF_URL__c</fullName>
        <description>URL used by the back to SF button</description>
        <inlineHelpText>Must be a relative url path (e.g. /home/home.jsp)</inlineHelpText>
        <label>Back to SF URL</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Almond Settings</label>
</CustomObject>

src/objects/Almond_Settings__c.object
    <fields>
        <fullName>Custom_Section_Name__c</fullName>
        <description>Name of a custom section displayed in the header</description>
        <inlineHelpText>Name of a custom section displayed in the header</inlineHelpText>
        <label>Custom Section Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>

src/objects/Almond_Settings__c.object
    <fields>
        <fullName>Custom_Section_URL__c</fullName>
        <description>URL path for your custom page</description>
        <inlineHelpText>URL for your custom page (e.g. https://instance.salesforce.com/apex/myhomepage)</inlineHelpText>
        <label>Custom Section URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Almond_Settings__c.object
    <fields>
        <fullName>Hide_Back_to_SF_Button__c</fullName>
        <inlineHelpText>Enable this option if you'd like to hide back to SF button when the SF header is disabled</inlineHelpText>
        <defaultValue>false</defaultValue>
        <label>Hide Back to SF Button</label>
        <type>Checkbox</type>
    </fields>

app/src/classes/LMSSettings.cls
/*
Copyright (c) 2014, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

*/
global with sharing class LMSSettings {

    /* Global settings - exposed to package extensions */

    global static String getCustomLogo(){
        return (String)getValue('Company_Logo__c',null);
    }

    global static String getHeaderBackgroundColor(){
        return (String)getValue('Header_Background_Color__c','#2A94D6');
    }

    global static String getHeaderTextColor(){
        return (String)getValue('Header_Text_Color__c','#DBE5F2');
    }

    global static String getHeaderTextHoverColor(){
        return (String)getValue('Header_Text_Hover_Color__c','#FFFFFF');
    }

    global static Boolean getShowSalesforceHeader(){
        return (Boolean)getValue('Show_Salesforce_Header__c',false);
    }

    global static String getBacktoSFUrl(){
        String defaultURL = '/home/home.jsp';
        if(LMSUtils.getCurrentNetworkId() != null){
            defaultURL = '/'+LMSUtils.getCurrentNetworkURLPath()+defaultURL;
        }
        return (String)getValue('Back_to_SF_URL__c',defaultURL);
    }

    /* Internal Settings - exposed to the current package only */

    public static Boolean getDisableTrackAchievements(){
        return (Boolean)getValue('Disable_Track_Achievements__c',false);
    }

    public static Boolean getDisableFutureProgressCalculation(){
        return (Boolean)getValue('Disable_Future_Progress_Calculation__c',false);
    }

    public static Boolean getEnableIOSTapFix(){
        return (Boolean)getValue('Enable_iOS_Tap_Fix__c',false);
    }

    public static Boolean getDisableCorrectResponseCheckbox(){
        return (Boolean)getValue('Disable_Correct_Response_Checkbox__c',false);
    }

    public static Boolean getDisableFeedItemAuditFields(){
        return (Boolean)getValue('Disable_Feed_Item_Audit_Fields__c',false);
    }

    public static String getCustomHeaderName(){
        return (String)getValue('Custom_Section_Name__c',null);
    }

    public static String getCustomHeaderURL(){
        return (String)getValue('Custom_Section_URL__c',null);
    }

    public static Boolean getHideBackToSFButton(){
        return (Boolean)getValue('Hide_Back_to_SF_Button__c',false);
    }

    private static Object getValue(String key, Object defaultValue){
        Almond_Settings__c cs = Almond_Settings__c.getInstance();
        if(cs != null && cs.get(key) != null){
            return cs.get(key);
        }else{
            return defaultValue;
        }
    }

}