app/src/objects/Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Progress_Percentage__c</fullName>
        <label>Progress %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Progress__c</fullName>
        <label>Progress</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Plan</label>
        <referenceTo>Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

custom/app/src/objects/LMS_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Activity_value__c</fullName>
        <label>How valuable was this activity?</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Confidence_customizing__c</fullName>
        <label>Confidence in customizing this content?</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Participant_Comments__c</fullName>
        <label>Participant Comments</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Support_Material_value__c</fullName>
        <label>How valuable were the support materials?</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_Spent_Preparing__c</fullName>
        <label>Time Spent Preparing for Badge (hrs)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Plan</label>
        <referenceTo>Training_Plan__c</referenceTo>
        <relationshipLabel>LMS Feedbacks</relationshipLabel>
        <relationshipName>LMS_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LMS_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LMS Feedback</label>
    <nameField>
        <displayFormat>F-{000000000}</displayFormat>
        <label>LMS Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LMS Feedbacks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Training_Plan__c.object
<CustomObject>
    <label>Training Plan</label>
    <nameField>
        <label>Training Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

custom/app/src/classes/TrainingPlanFeedbackController.cls
public with sharing class TrainingPlanFeedbackController {
	public LMS_Feedback__c lmsfeedback {get; set;}
	public String tplanname {get; set;}
	private String assignmentId {get; set;}
	private String trainingplanId {get; set;}
	public Boolean hasMessages{get{return ApexPages.hasMessages();}}
	public String lmstemplate {get; set;}

	public TrainingPlanFeedbackController(){
		assignmentId = ApexPages.CurrentPage().getParameters().get('aid');
		trainingplanId = ApexPages.CurrentPage().getParameters().get('tid');
		lmsfeedback = new LMS_Feedback__c();
		lmstemplate = LMSUtils.isMobileDevice() ? 's1LMS_Template' : 'LMS_Template';

    	if(String.isnotBlank(assignmentId) && String.isnotBlank(trainingplanId)){
    		assignmentId = string.escapeSingleQuotes(assignmentId);
    		Learning_Assignment__c la = [select Id, Training_Plan__c, Training_Plan__r.Name, User__c from Learning_Assignment__c where Id =:assignmentId ];

    		tplanname = la.Training_Plan__r.Name;
    		lmsfeedback.Training_Plan__c = la.Training_Plan__c;
    		lmsfeedback.User__c = la.User__c;

    	}else{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There was an error with loading feedback, please contact your system administrator.'));
    	}
	}

	public PageReference save() {

		try{
			if(lmsfeedback.Activity_value__c == null || lmsfeedback.Confidence_customizing__c == null || lmsfeedback.Support_Material_value__c == null || lmsfeedback.Time_Spent_Preparing__c == null || String.isBlank(lmsfeedback.Participant_Comments__c) ){
				LMSUtils.addErrorMessage('All fields are required.');
				return null;
			}

			lmsfeedback.OwnerId = UserInfo.getUserId();
			insert lmsfeedback;

			Learning_Assignment__c la = new Learning_Assignment__c( Id = assignmentId);
			la.Progress__c = 'Completed';
			la.Progress_Percentage__c = 100;
			update la;

		}catch(Exception e){
			LMSUtils.addErrorMessage(e.getMessage());
            return null;
		}

		return redirectToPlanDetail();
	}

	public PageReference cancel(){
        return redirectToPlanDetail();
    }

    public PageReference redirectToPlanDetail(){
    	PageReference ref = LMSUtils.isMobileDevice() ? Page.s1TrainingPlanDetail : Page.TrainingPlanDetail;
        ref.getParameters().put('id',trainingplanId);
        ref.getParameters().put('aid',assignmentId);
        ref.setRedirect(true);
        return ref;
    }

}