app/src/objects/Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Learning_Version__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Learning Version</label>
        <referenceTo>Learning_Version__c</referenceTo>
        <relationshipLabel>Learning Assignments (Learning Version)</relationshipLabel>
        <relationshipName>Learning_Assignments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Progress_Percentage__c</fullName>
        <label>Progress %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Progress__c</fullName>
        <label>Progress</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Training_Plan_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Plan Section</label>
        <referenceTo>Training_Plan_Section__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Plan</label>
        <referenceTo>Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

app/src/objects/Learning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Learning Versions</relationshipLabel>
        <relationshipName>Learning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Version</label>
    <nameField>
        <displayFormat>LEV-{0000000}</displayFormat>
        <label>Learning Version ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Plan__c.object
<CustomObject>
    <label>Training Plan</label>
    <nameField>
        <label>Training Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Training_Plan_Section__c.object
<CustomObject>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <label>Training Plan</label>
        <referenceTo>Training_Plan__c</referenceTo>
        <relationshipLabel>Training Plan Sections</relationshipLabel>
        <relationshipName>Training_Plan_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Training Plan Section</label>
    <nameField>
        <label>Training Plan Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Plan Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

custom/app/src/classes/s1SubmitBioController.cls
public with sharing class s1SubmitBioController {

    public String description{get;set;}
    public String hobbies{get;set;}
    public Id imageId{get;private set;}
    
    public String distList{get;set;}
    public String assignmentId{get;private set;}
    public Boolean hasMessages{get{return ApexPages.hasMessages();}}
    public User curUser{get;private set;}
    
    public Boolean isCompleted{get;private set;}
    
    private Id trainingPlanId;
    private Learning_Assignment__c currentAssignment;

    public s1SubmitBioController(){
        init();
    }
    
    private void init(){
        assignmentId = ApexPages.currentPage().getParameters().get('aid');
        description = null;
        isCompleted = false;
        hobbies = null;
        distList= null;
        currentAssignment = null;
        //Get additional user info
        curUser = [select id,name,email,phone,title from User where id = :UserInfo.getUserId()];
        //Get additional assignment info
        //Get more info for current assignment
        List<Learning_Assignment__c> assignments = [select id
                                                        ,Training_Plan_Section__c
                                                        ,Training_Plan__c
                                                        ,Progress__c
                                                        from Learning_Assignment__c 
                                                        where id = :assignmentId];
                                                        
        if(assignments.size()>0){
            currentAssignment = assignments.get(0);
            if(currentAssignment.Progress__c == 'Completed'){
            	isCompleted = true;
            }
        }             
        
        imageId = getUserImage();                 
    }
    
    
    public PageReference submitBio(){
        return sendEmail();
    }
    
    private PageReference sendEmail(){
        
        if(String.isBlank(distList)|| String.isBlank(description)  || String.isBlank(hobbies)){
            LMSUtils.addErrorMessage('Please fill-in all required fields');
            return null;
        }else{
            try{
                String[] toAddresses = new String[] {curUser.email,distList};
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                
                //mail.setTargetObjectId(UserInfo.getUserId());
                
                mail.setToAddresses(toAddresses);
                mail.setSubject('Hello World from '+UserInfo.getName());
                mail.setSenderDisplayName('Salesforce.com On-boarding');
                mail.setUseSignature(false);
                mail.setBccSender(false);
                mail.setSaveAsActivity(true);
                
                String emailBody = '<body>';
                
                emailBody += '<h1>'+UserInfo.getName()+'</h1>';
                emailBody += '<br/>';
                emailBody += '<h2>About Me :</h2>';
                emailBody += '<p>'+description+'</p>';
                emailBody += '<h2>Hobbies :</h2>';
                emailBody += '<p>'+hobbies+'</p>';            
                
                emailBody += '</body>';
    
                mail.setHtmlBody(emailBody);
                
                List<Attachment> atts =[ select body from Attachment where id = :imageId];
                
                if(atts.size()>0){
                	Attachment att = atts.get(0);
	                Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
	                efa.setFileName('HelloWorld.png');
	                efa.setBody(att.body);
	                mail.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
                }
                
                Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});  
                
                Learning_Assignment__c asgmt = new Learning_Assignment__c(id=assignmentId);
                asgmt.Progress__c = 'Completed';
                asgmt.Progress_Percentage__c = 100;
                update asgmt;
                
				return redirectToPlanDetail();
            
            }catch(Exception e){
                ApexPages.addMessages(e);
                return null;
            }

        }

    }
    
	public PageReference cancelSubmission(){
		return redirectToPlanDetail();
	}
	
	private PageReference redirectToPlanDetail(){
		PageReference ref = Page.TrainingPlanDetail;
		if(LMSUtils.isMobileDevice()){
			ref = Page.s1TrainingPlanDetail;
		}
	    ref.getParameters().put('id',trainingPlanId);
	    ref.getParameters().put('aid',assignmentId);
	    ref.setRedirect(true);
	    return ref;		
	}
	
    private Id getUserImage(){

        Id result = null;
        
        if(currentAssignment != null){

            trainingPlanId = currentAssignment.Training_Plan__c;
            ID sectionId = currentAssignment.Training_Plan_Section__c;
            
            if(sectionId != null){
                //Get learning assignment for the task with picture
                List<Learning_Assignment__c> imageAssignments = [select id
                                                                ,Name 
                                                                from Learning_Assignment__c 
                                                                where Training_Plan_Section__c = :sectionId
                                                                and User__c = :UserInfo.getUserId()
                                                                and Learning_Version__r.Task__r.Enable_Image_Upload__c = true
                                                                order by CreatedDate asc];
                
                if(imageAssignments.size()>0){                                 
                    Learning_Assignment__c imageAssignment = imageAssignments.get(0);
                    if(imageAssignment != null){
                        //Fetch attachment from assignment
                        List<Attachment> attachments = [select id from Attachment where ParentId = :imageAssignment.Id];
                        if(attachments.size()>0){
                            result = attachments.get(0).Id;
                        }
                    }
                }
            }
        }
        
        return result;
    }
}