app/src/objects/Learning__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learnings</pluralLabel>
    <recordTypes>
        <fullName>Quiz</fullName>
        <active>true</active>
        <description>Quiz</description>
        <label>Quiz</label>
    </recordTypes>
    <recordTypes>
        <fullName>Resource</fullName>
        <active>true</active>
        <description>Resource</description>
        <label>Resource</label>
    </recordTypes>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>Task</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>

</CustomObject>

app/src/objects/Learning_Category__c.object
<CustomObject>
    <fields>
        <fullName>Background_Image_URL__c</fullName>
        <label>Background Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Text_Color__c</fullName>
        <label>Text Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Learning Category</label>
    <nameField>
        <label>Learning Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

app/src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>QTN-{0000000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question_Line__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question Line</label>
    <nameField>
        <label>Question Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/src/objects/Quiz__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Learning__c</fullName>
        <label>Learning</label>
        <referenceTo>Learning__c</referenceTo>
        <relationshipLabel>Quizzes</relationshipLabel>
        <relationshipName>Quizzes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizzes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Learning__c</fullName>
        <label>Learning</label>
        <referenceTo>Learning__c</referenceTo>
        <relationshipLabel>Task</relationshipLabel>
        <relationshipName>Task</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/src/objects/Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Background_Color__c</fullName>
        <label>Background Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Background_Image_URL__c</fullName>
        <inlineHelpText>URL for the image displayed in the training plan detail header</inlineHelpText>
        <label>Background Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Text_Color__c</fullName>
        <label>Text Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Training Plan</label>
    <nameField>
        <label>Training Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Training_Plan_Category__c.object
<CustomObject>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <label>Training Plan</label>
        <referenceTo>Training_Plan__c</referenceTo>
        <relationshipLabel>Training Plan Categories</relationshipLabel>
        <relationshipName>Training_Plan_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Training Plan Category</label>
    <nameField>
        <displayFormat>TPC-{0000000}</displayFormat>
        <label>Training Plan Category ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Plan Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/src/objects/Training_Plan_Section__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <label>Training Plan</label>
        <referenceTo>Training_Plan__c</referenceTo>
        <relationshipLabel>Training Plan Sections</relationshipLabel>
        <relationshipName>Training_Plan_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Training Plan Section</label>
    <nameField>
        <label>Training Plan Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Plan Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/src/objects/Training_Plan_Section_Item__c.object
<CustomObject>
    <fields>
        <fullName>Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <referenceTo>Learning__c</referenceTo>
        <relationshipLabel>Training Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Training Plan Section Item</label>
    <nameField>
        <displayFormat>TPSI-{0000000}</displayFormat>
        <label>Training Plan Section Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Plan Section Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/src/objects/Training_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Training Resource</label>
    <nameField>
        <label>Training Resource Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/src/objects/Training_Track__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>Achievement__c</referenceTo>
        <relationshipLabel>Training Track</relationshipLabel>
        <relationshipName>Training_Track</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Background_Color__c</fullName>
        <label>Background Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Background_Image_URL__c</fullName>
        <label>Background Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Text_Color__c</fullName>
        <label>Text Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Training Track</label>
    <nameField>
        <label>Training Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

app/src/objects/Training_Track_Level__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Track__c</fullName>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Training Track Levels</relationshipLabel>
        <relationshipName>Training_Track_Levels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Training Track Level</label>
    <nameField>
        <label>Training Track Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Track Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/src/objects/Training_Track_Level_Item__c.object
<CustomObject>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Plan</label>
        <referenceTo>Training_Plan__c</referenceTo>
        <relationshipLabel>Training Track Level Items</relationshipLabel>
        <relationshipName>Training_Track_Level_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Track_Level__c</fullName>
        <label>Training Track Level</label>
        <referenceTo>Training_Track_Level__c</referenceTo>
        <relationshipLabel>Training Track Level Items</relationshipLabel>
        <relationshipName>Training_Track_Level_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
        <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Training Track Level Item</label>
    <nameField>
        <displayFormat>TTLI-{0000000}</displayFormat>
        <label>Training Track Level Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Track Level Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/src/classes/TestTrainingTrackData.cls
/*
Copyright (c) 2014, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

*/
@isTest
public class TestTrainingTrackData {

	public static List<Training_Track__c> createTrainingTracks(List<TestParams.TrainingTrackParam> params){
		List<Training_Track__c> lResult = new List<Training_Track__c>();
		for(TestParams.TrainingTrackParam p : params){
			Training_Track__c ttrack = new Training_Track__c();
			ttrack.Name = p.Name;
			ttrack.Description__c = p.Description;
			ttrack.Status__c = p.status;
			ttrack.Background_Color__c = p.backgroundColor;
			ttrack.Background_Image_URL__c = p.backgroundImageURL;
			ttrack.Text_Color__c = p.textColor;
			ttrack.Achievement__c = p.achievementId;
			lResult.add(ttrack);
		}
		insert lResult;
		return lResult;
	}

	public static List<Training_Track_Level_Item__c> createTrainingTrackItems(String trackId, List<Training_Plan__c> tplans, Integer level){
		List<Training_Track_Level_Item__c> lResult = new List<Training_Track_Level_Item__c>();

		//Create level
		Training_Track_Level__c ttlevel = new Training_Track_Level__c();
		ttlevel.Order__c = level;
		ttlevel.Training_Track__c = trackId;
		ttlevel.Description__c = 'test';
		insert ttlevel;

		//Create items
		for(Training_Plan__c tplan : tplans){
			Training_Track_Level_Item__c ttrackItem = new Training_Track_Level_Item__c();
			ttrackItem.Training_Track_Level__c = ttlevel.Id;
			ttrackItem.Training_Plan__c = tplan.Id;
			lResult.add(ttrackItem);
		}
		insert lResult;
		return lResult;
	}

	public static void createSampleData(){

		//Create quiz learnings
		List<Learning__c> quizLearnings = TestLearningData.createTestLearning(1, 'Quiz', false);
		//create resource learnings
		List<Learning__c> resourceLearnings = TestLearningData.createTestLearning(3, 'Resource', false);
		//create task learnings
		List<Learning__c> taskLearnings = TestLearningData.createTestLearning(3, 'Task', false);
		//create quiz
		List<Quiz__c> quiz = TestLearningData.createTestQuiz(quizLearnings);
		//create question line
		List<Question_Line__c> qline = TestLearningData.createTestQuestionLine(quiz, 3);
		//create question
		List<Question__c> question = TestLearningData.createTestQuestions(qline, 4);
		//create training resources
		List<Training_Resource__c> tresources = TestLearningData.createTestTrainingResource(resourceLearnings);
		//create task resources
		List<Task__c> ttasks = TestLearningData.createTestTask(taskLearnings);
		//create learning categories
		List<Learning_Category__c> learningCategories = TestLearningData.createTestLearningCategories(2);

		//Publish learnings
		for(Integer i = 0;i < quizLearnings.size();i++){
			TestLearningData.publishLearning(quizLearnings.get(i).Id,'quiz',quiz.get(i).Id,false);
		}
		for(Integer i = 0;i < resourceLearnings.size();i++){
			TestLearningData.publishLearning(resourceLearnings.get(i).Id,'resource',tresources.get(i).Id,false);
		}
		for(Integer i = 0;i < taskLearnings.size();i++){
			TestLearningData.publishLearning(taskLearnings.get(i).Id,'task',ttasks.get(i).Id,false);
		}

		//Create training plans
		TestParams.TrainingPlanParam tplan1 = new TestParams.TrainingPlanParam();
		TestParams.TrainingPlanParam tplan2 = new TestParams.TrainingPlanParam();
		TestParams.TrainingPlanParam tplan3 = new TestParams.TrainingPlanParam();
		List<Training_Plan__c> tplans = TestTrainingPlanData.createTrainingPlans(new List<TestParams.TrainingPlanParam>{tplan1,tplan2,tplan3});

		//Add learning categories to training plan
		List<Training_Plan_Category__c> tplanCategories = TestTrainingPlanData.createTrainingPlanCategories(tplans,learningCategories);

		//Create training plan sections
		List<Training_Plan_Section__c> tplanSections1 = TestTrainingPlanData.createTrainingPlanSections(tplans.get(0).Id,1);
		List<Training_Plan_Section__c> tplanSections2 = TestTrainingPlanData.createTrainingPlanSections(tplans.get(1).Id,2);
		List<Training_Plan_Section__c> tplanSections3 = TestTrainingPlanData.createTrainingPlanSections(tplans.get(2).Id,1);


		//Create training plan section items for quizzes
		List<Training_Plan_Section_Item__c> tplan1SectionItems1 = TestTrainingPlanData.createTrainingPlanSectionItems(tplanSections1.get(0).Id,quizLearnings);

		List<Training_Plan_Section_Item__c> tplan2SectionItems1 = TestTrainingPlanData.createTrainingPlanSectionItems(tplanSections2.get(0).Id,resourceLearnings);
		List<Training_Plan_Section_Item__c> tplan2SectionItems2 = TestTrainingPlanData.createTrainingPlanSectionItems(tplanSections2.get(1).Id,taskLearnings);

		List<Training_Plan_Section_Item__c> tplan3SectionItems1 = TestTrainingPlanData.createTrainingPlanSectionItems(tplanSections3.get(0).Id,resourceLearnings);

		//Create a training track
		TestParams.TrainingTrackParam ttrack1 = new TestParams.TrainingTrackParam();
		List<Training_Track__c> ttracks = createTrainingTracks(new List<TestParams.TrainingTrackParam>{ttrack1});

		//Add training track items
		List<Training_Track_Level_Item__c> trackItems1 = createTrainingTrackItems(ttracks.get(0).Id,new List<Training_Plan__c>{tplans.get(0)},1);
		List<Training_Track_Level_Item__c> trackItems2 = createTrainingTrackItems(ttracks.get(0).Id,new List<Training_Plan__c>{tplans.get(1),tplans.get(2)},2);
	}

}