app/src/objects/Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Training Plan</label>
    <nameField>
        <label>Training Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

app/src/objects/Training_Plan_Batch_Operation__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Information__c</fullName>
        <label>Additional Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Errors__c</fullName>
        <label>Errors</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Successes__c</fullName>
        <label>Successes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <label>Training Plan</label>
        <referenceTo>Training_Plan__c</referenceTo>
        <relationshipLabel>Training Plan Batch Operations</relationshipLabel>
        <relationshipName>Training_Plan_Batch_Operations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Upsert Assignments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete Assignments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update Assignments</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Training Plan Batch Operation</label>
    <nameField>
        <displayFormat>TPBO-{0000000}</displayFormat>
        <label>Training Plan Batch Operation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Plan Batch Operations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/src/classes/TrainingPlanAssignmentExtensionBatch.cls
/*
Copyright (c) 2014, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

*/
public with sharing class TrainingPlanAssignmentExtensionBatch{

    private String trainingPlanId;
    public Boolean hasMessages{get{return ApexPages.hasMessages();}}

    public TrainingPlanAssignmentExtensionBatch(ApexPages.StandardController cont){
        trainingPlanId = cont.getRecord().Id;
        init();
    }

    private void init(){
        //Nothing to do here for now...
    }

    public PageReference updateAllAssignments(){

        checkBatchOperationAccess();

        Training_Plan_Batch_Operation__c tpbo;
        try{

            tpbo = new Training_Plan_Batch_Operation__c();
            tpbo.Training_Plan__c = trainingPlanId;
            tpbo.Type__c = 'Update Assignments';
            tpbo.Successes__c = 0;
            tpbo.Status__c = 'New';
            tpbo.Errors__c = 0;
            tpbo.Additional_Information__c = null;
            insert tpbo;

            Id batchInstanceId = Database.executeBatch(new TrainingPlanAssignmentsUpdateBatch(trainingPlanId,tpbo.Id),20);
            LMSUtils.addSuccessMessage('Batch update process has been queued successfully');
        }catch(Exception e){
            tpbo.Status__c = 'Failed';
            tpbo.Additional_Information__c = e.getMessage();
            update tpbo;
            ApexPages.addMessages(e);
        }
        return null;
    }

    public PageReference deleteAllAssignments(){

        checkBatchOperationAccess();

        Training_Plan_Batch_Operation__c tpbo;
        try{

            tpbo = new Training_Plan_Batch_Operation__c();
            tpbo.Training_Plan__c = trainingPlanId;
            tpbo.Type__c = 'Delete Assignments';
            tpbo.Successes__c = 0;
            tpbo.Status__c = 'New';
            tpbo.Errors__c = 0;
            tpbo.Additional_Information__c = null;
            insert tpbo;

            Id batchInstanceId = Database.executeBatch(new TrainingPlanAssignmentsDeleteBatch(trainingPlanId,tpbo.Id),20);
            LMSUtils.addSuccessMessage('Batch delete process has been queued successfully');
        }catch(Exception e){
            tpbo.Status__c = 'Failed';
            tpbo.Additional_Information__c = e.getMessage();
            update tpbo;
            ApexPages.addMessages(e);
        }
        return null;
    }

    //TODO : DRY up these access checks, move them to a base class
    private void checkBatchOperationAccess(){
        //BEGIN Access Check
        Map<Schema.sObjectType,List<String>> relatedFieldsObjects = new Map<Schema.sObjectType,List<String>>();
        relatedFieldsObjects.put(Training_Plan_Batch_Operation__c.sObjectType,new List<String>{
            'Type__c'
            ,'Successes__c'
            ,'Status__c'
            ,'Errors__c'
            ,'Additional_Information__c'
        });
        LMS_ESAPI.isAuthorizedToUpdate(relatedFieldsObjects);
        //END Access Check
    }

}